apiVersion: v1
kind: Service
metadata:
  name: nanoprobe-lab-service
spec:
  selector:
    app: nanoprobe-lab
  ports:
  - name: web
    port: 5000
    targetPort: 5000
  - name: api
    port: 8000
    targetPort: 8000
  type: LoadBalancer
